name: Update iCal File

on:
  schedule:
    - cron: "0 0 */2 * *"  # Alle zwei Tage um Mitternacht
  workflow_dispatch:  # Ermöglicht manuelles Starten

permissions:
  contents: write

jobs:
  update-ical:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # oder 'zulu', je nachdem, welche Distribution du verwenden möchtest
          java-version: '17' # die gewünschte Java-Version

      - name: Build and run JAR
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_HOST: ${{ secrets.API_HOST }}
          API_URL_oldMatches: ${{ secrets.API_URL_oldMatches }}
          API_URL_upcomingMatches: ${{ secrets.API_URL_upcomingMatches }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
        run: |
          mvn package
          java -jar target/SportsCalenderGenerate-1.jar

      - name: Commit and Push updated iCal file
        run: |
          git config --global user.name "GitHub Calender Bot"
          git config --global user.email ""
          git add calenderOutput/newCal.ics
          git commit -m "Update iCal file"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
